### PR TITLE
Using the same color as other Nintendo systems

### PR DESCRIPTION
**Pull request by meleu**

### CODE REVIEW

**Comment by bobbycopter** [comment]
This goes also for n64 and virtual boy. Both are set to f20000. Nes in master is still set to f20000.

**Comment by meleu** [comment]
Indeed. I saw @lilbud changed it again (accidentaly?) when added video support.

**Comment by lilbud** [comment]
I didn't even touch the individual theme.xml files when adding video support. I'm not sure what happened.

**Comment by meleu** [comment]
I think you uploaded an old version of the files, before this PR here.

**Comment by lilbud** [comment]
Could you submit a new PR? I only touched the main theme.xml, so im not sure what happened.

**Comment by meleu** [comment]
Yeah. I'll do it.
Look what you did in 13-Feb-2017: https://github.com/lilbud/es-theme-flat/commit/f4b9d50adc5c2447f4318ba5aaef1dbc2bc633d7

**Comment by lilbud** [comment]
Ok, I don't remember doing that. But I usually have a bad memory when it comes to these things.

**Comment by meleu** [comment]
> Could you submit a new PR?

Done: #5

**Pull request merged**
